# Generated by Django 5.2.1 on 2026-06-10 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_follow'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='follow',
            new_name='core_follow_followe_986d95_idx',
            old_name='core_follow_follower_idx',
        ),
        migrations.RenameIndex(
            model_name='follow',
            new_name='core_follow_followi_a11b6b_idx',
            old_name='core_follow_following_idx',
        ),
    ]
