# Generated by Django 5.2.1 on 2025-05-11 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisteredUsers',
            new_name='RegisteredUser',
        ),
    ]
