# Generated by Django 5.2.1 on 2025-05-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_registeredusers_registereduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='first_name',
            field=models.CharField(default='John', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registereduser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='last_name',
            field=models.CharField(default='Doe', max_length=150),
            preserve_default=False,
        ),
    ]
