# Generated by Django 5.2.1 on 2025-07-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(default='proj-ae4c9d463ff5', editable=False, max_length=20, unique=True),
        ),
    ]
