# Generated by Django 5.2.1 on 2025-07-02 17:28

import django.db.models.deletion
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_project_description_project_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codefile',
            old_name='filename',
            new_name='name',
        ),
        migrations.AddField(
            model_name='codefile',
            name='item_type',
            field=models.CharField(choices=[('file', 'File'), ('folder', 'Folder')], default='file', max_length=10),
        ),
        migrations.AddField(
            model_name='codefile',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.codefile'),
        ),
        migrations.AlterField(
            model_name='codefile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=projects.models.upload_to_project),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(default='proj-0654cd2604ed', editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
