# Generated by Django 5.2.1 on 2025-07-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_forks_project_issues_project_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='auto_init',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='boards_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='gitignore',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='issues_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='license',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='template',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='wiki_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='discussions_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
