# Generated by Django 5.2.1 on 2025-07-11 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_auto_init_project_boards_enabled_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
