# Generated by Django 5.2.1 on 2025-08-28 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_issue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(choices=[('Bug Report', 'bug report'), ('Feature Request', 'feature request'), ('Improvement', 'improvement'), ('Question', 'question')], default='Bug Report', max_length=20),
        ),
        migrations.AddField(
            model_name='issue',
            name='labels',
            field=models.CharField(default='bug', max_length=20),
        ),
        migrations.AddField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('Low', 'low'), ('Medium', 'medium'), ('High', 'high'), ('Critical', 'critical')], default='medium', max_length=8),
        ),
        migrations.AddField(
            model_name='issue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
