# Generated by Django 5.2.1 on 2025-08-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_issue_assigned_to_issue_issue_type_issue_labels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='labels',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
