# Generated by Django 5.2.1 on 2025-09-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_pullrequest_is_draft_pullrequest_labels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('to_do', 'To Do'), ('review', 'Review')], default='to_do', max_length=20),
        ),
    ]
