# Generated by Django 5.2.1 on 2025-09-06 15:32

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_projecttask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='task_id',
            field=models.CharField(default=projects.models.generate_task_id, editable=False, max_length=20, unique=True),
        ),
    ]
