# Generated by Django 5.2.1 on 2025-09-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_projecttask_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('to_do', 'To Do'), ('review', 'Review'), ('done', 'Done')], default='to_do', max_length=20),
        ),
    ]
