# Generated by Django 5.2.1 on 2026-02-14 16:15

import datetime
import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_projecttask_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
        migrations.AddField(
            model_name='projectinvite',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 18, 16, 15, 35, 889746, tzinfo=datetime.timezone.utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectinvite',
            name='role_to_assign',
            field=models.CharField(choices=[('admin', 'Admin'), ('maintainer', 'Maintainer'), ('developer', 'Developer'), ('guest', 'Guest')], default='developer', max_length=15),
        ),
        migrations.AddField(
            model_name='projectinvite',
            name='token',
            field=models.CharField(default=projects.models.generate_invite_token, editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(choices=[('bug_report', 'Bug Report'), ('feature_request', 'Feature Request'), ('improvement', 'Improvement'), ('question', 'Question')], default='Bug Report', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='discussions_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='projectinvite',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprojectrole',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('maintainer', 'Maintainer'), ('developer', 'Developer'), ('guest', 'Guest')], max_length=15),
        ),
    ]
