# Generated by Django 5.2.1 on 2026-04-13 09:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_fix_project_creator_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussionthread',
            options={'ordering': ['-last_activity']},
        ),
        migrations.AddField(
            model_name='discussionthread',
            name='comment_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='discussionthread',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='discussionthread',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discussionthread',
            name='labels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='discussionthread',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='discussionthread',
            name='thread_id',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='discussionthread',
            name='thread_type',
            field=models.CharField(choices=[('feature', 'Feature Request'), ('bug', 'Bug Report'), ('fix', 'Fix'), ('improvement', 'Improvement'), ('question', 'Question'), ('discussion', 'Discussion'), ('documentation', 'Documentation')], default='discussion', max_length=20),
        ),
        migrations.AddField(
            model_name='discussionthread',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='discussionthread',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_discussions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DiscussionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(blank=True, editable=False, max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.discussionthread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
