# Generated by Django 5.2.1 on 2026-06-22 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_notification_notification_type_notification_title_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
